project:
  type: website

website:
  title: "PlotWorkshop"
  navbar:
    left:
      - text: Tag 1
        icon: flower3
        menu:
        - text: "Einf端hrung"
          href: sessions/Einf端hrung/Einf端hrung.qmd
          icon: book-fill
        - text: "ggplot2: Die Basics"
          href: sessions/ggplot_intro/ggplot2_basics.qmd
          icon: bar-chart-fill
        - text: "R f端r Grafiken"
          href: sessions/r_basics/r_basics.qmd
          icon: r-circle-fill
        - text: "Gute Plots"
          href: sessions/good_plots/good_plots.qmd
          icon: pie-chart-fill
      
      - text: Tag 2
        icon: tree-fill
        menu:
        - text: "ggplot2: Advanced"
          href: sessions/more_ggplot/more_ggplot.qmd
          icon: bar-chart-steps
        - text: "gganimate & plotly"
          href: sessions/animate_plotly/animate_plotly.qmd
          icon: arrows-move
        - text: "Exportieren"
          href: sessions/science_plots/science_plots.qmd
          icon: mortarboard-fill
        - text: "Abschluss"
          href: sessions/exercise/exercise.qmd
          icon: person-arms-up
        - text: "Karten"
          href: sessions/good_plots/maps.qmd
          icon: map-fill
    right:
      - text: "Die Daten"
        href: other_sites/daten.qmd     
        icon: database-fill
      - text: "Ressourcen"
        href: other_sites/Ressourcen.qmd     
        icon: folder-fill 
      
format:
  html:
    theme: styles.scss
    toc: true
    embed-resources: true


  letterbox-revealjs:
    embed-resources: true
    theme: 
      - styles.scss
    highlight-style: dark.theme
    fontsize: 20pt
    code-block-height: 100px
    slide-level: 2
    toc-depth: 3

code-link: true
code-line-numbers: false
execute: 
  fig-width: 5
  fig-height: 5
  echo: true
callout-appearance: simple
lang: de
csl: apa7.csl

editor: source