project:
  type: website

website:
  title: "PlotWorkshop"
  navbar:
    left:
      - text: Themen
        menu: 
          - text: Einführung
            href: sessions/Einführung/Einführung.qmd

format:
  html:
    theme: styles_light.scss
    toc: true

  letterbox-revealjs:
    embed-resources: true
    theme: styles.scss
    highlight-style: light.theme

code-link: true
code-line-numbers: false
execute:
  echo: true
callout-appearance: simple
lang: de
csl: apa7.csl

editor: source

