on:
  workflow_dispatch:
  push:
    branches: main
  pull_request:
    branches: [main]

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: update packages
        run: sudo apt-get update
      - name: Install libstuff
        run: sudo apt-get install libudunits2-dev
      - name: Install system dependencies for sf
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libproj-dev \
            libgeos-dev \
            libgdal-dev
      - name: Install libcurl
        run: sudo apt-get install libcurl4-openssl-dev
      - name: Install libharfbuzz  
        run: sudo apt-get install libharfbuzz-dev libfribidi-dev
      - name: Install GSL development package
        run: sudo apt install libgsl-dev
      - name: Intsall libmagick
        run: sudo apt-get install libmagick++-dev
      - name: Install libglpk-dev
        run: sudo apt-get install libglpk-dev
      - name: Install gifski
        run: sudo snap install gifski
      
        
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.5.0'

      - name: Install R Dependencies
        uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 1

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}